### ISSUE TITLE
List of compatible routers and state of the project?

### ISSUE THREAD

**Issue by nathanl** [EFForg/OpenWireless#286]
I saw [this post](https://www.eff.org/deeplinks/2014/07/building-open-wireless-router) a while back and bookmarked it. It said "Currently the software runs on one specific model of hardware (the Netgear WNDR3800)". I was about to buy one, then saw that Amazon lists WNDR4300 as its successor. I don't know whether it's supported.

Openwireless.org is all about the movement, and this project's README talks about building the software. Does any place list the "in between" level of detail: whether the software is ready for use and what devices it's been tested on?

**Comment by Rangak** [comment]
The WNDR4300 is not yet supported, but I have done some work for it and it is on the roadmap. Currently the WNDR3800 is the the only device for which binaries have been released. In the next 2-3 months I hope to announce support for additional models. 
The latest release is an alpha and suitable for use a your primary home router. I have been using it as such for a few months in my home. It is an alpha primarily because there are 
planned features that are as yet unimplemented. The beta release is in planning and you can check the issues on github for details https://github.com/EFForg/OpenWireless/issues?q=is%3Aopen+is%3Aissue+milestone%3Abeta . Help is welcome !
